LOAD DATABASE
    FROM sqlite:///absolute/path/to/e-hentai.db
    INTO postgresql://user:password@localhost:5432/ehentai_db

WITH include drop, create tables, create indexes, reset sequences,
     workers = 8, concurrency = 4

SET PostgreSQL PARAMETERS
    maintenance_work_mem to '512MB',
    work_mem to '128MB'

CAST type integer to bigint using integer-to-string,
     type tinyint to smallint using integer-to-string,
     type varchar to text drop typemod,
     type char to text drop typemod

BEFORE LOAD DO
    $$ DROP SCHEMA IF EXISTS e_hentai_db CASCADE; $$,
    $$ CREATE SCHEMA e_hentai_db; $$

AFTER LOAD DO
    $$ ALTER TABLE public.gallery SET SCHEMA e_hentai_db; $$,
    $$ ALTER TABLE public.tag SET SCHEMA e_hentai_db; $$,
    $$ ALTER TABLE public.torrent SET SCHEMA e_hentai_db; $$,
    $$ ALTER TABLE public.gid_tid SET SCHEMA e_hentai_db; $$;
